server:
  port: 8000

spring:
  application:
    name: dubbo-server
  profiles:
    active: dev

dubbo:
  application:
    logger: slf4j
    metadata-type: remote
    qos-enable: true
    qos-port: 22223
    qos-accept-foreign-ip: false
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    parameters:
      namespace: ${spring.profiles.active}
    register-mode: instance
  protocol:
    name: tri
    port: 50052